export const REVIEWS_SELECTOR = '#reviews-list > li'
export const AVATAR_SELECTOR = '.review-profile-photo img'
export const NAME_SELECTOR = '.review-writer-nickname'
export const REGION_SELECTOR = '.review-writer-region-name'
export const CONTENT_SELECTOR = '.review-content'
export const TIME_SELECTOR = '.review-time'
