export const PERSONAL_SELECTOR = '#user-profile'
export const NAME_SELECTOR = '#nickname'
export const REGION_SELECTOR = '#region_name'
export const AVATAR_SELECTOR = '#profile-image > img'
export const TEMPERATURE_SELECTOR = '.profile-detail-count'
