export const ITEMS_SELECTOR = '#smb-wrap'
export const ITEM_SELECTOR = '.flat-card'
export const ID_SELECTOR = '.smb-link'
export const IMAGE_SELECTOR = '.card-photo img'
export const LIKE_SELECTOR = '.smb-watch'
export const REVIEW_SELECTOR = '.smb-review'
export const TITLE_SELECTOR = '.smb-name'
export const REGION_CATEGORY_SELECTOR = '.smb-region-category-text'
